### ISSUE TITLE
Transition in background tab

### ISSUE THREAD

**Issue by baopham** [michaelvillar/dynamics.js#22]
Seems like transition doesn't continue if the tab becomes inactive. I suppose this is the browser thing, but is there a way to get around this?

**Comment by michaelvillar** [comment]
This is made on purpose. The reason is that `requestAnimationFrame` isn't working in background tabs. This is why `dynamics.setTimeout` exists too, it'll delay the setTimeout if the tab goes to the background.

One workaround would be to use `setInterval` when the tab goes to the background, but I don't think I'll work on this anytime soon.

Thanks!
